---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: computer-system-team-06
  labels:
    app: frontend
    dash.ulagbulag.io/subject: mobilex-exp
spec:
  selector:
    matchLabels:
      app: frontend
      dash.ulagbulag.io/subject: mobilex-exp
  template:
    metadata:
      labels:
        app: frontend
        dash.ulagbulag.io/subject: mobilex-exp
    spec:
      containers:
        - name: server
          image: duckracoon/bridge-react-image:v0.1
          env:
            - name: FRONTEND_CLIENT__BASE_URL
              value: http://backend:8000
          ports:
            - name: http
              protocol: TCP
              containerPort: 8501
          volumeMounts:
            - name: media-volume
              mountPath: /data/media
      volumes:
        - name: media-volume
          hostPath:
            path: /data/media
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: computer-system-team-06
  labels:
    app: frontend
    dash.ulagbulag.io/subject: mobilex-exp
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 8501
      targetPort: 8501
